// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TCC_API.Models.Entities
{
    [Index("CarId", Name = "IX_CarId")]
    [Index("ParkingId", Name = "IX_ParkingId")]
    [Index("VacancyId", Name = "IX_VacancyId")]
    public partial class ParkingReservationHistory : Base
    {
        public Guid ParkingId { get; set; }
        public Guid VacancyId { get; set; }
        public Guid CarId { get; set; }
        public int VacancyType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CommittedStartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CommittedEndDate { get; set; }

        [ForeignKey("CarId")]
        [InverseProperty("ParkingReservationHistory")]
        public virtual Car Car { get; set; }
        [ForeignKey("ParkingId")]
        [InverseProperty("ParkingReservationHistory")]
        public virtual Parking Parking { get; set; }
        [ForeignKey("VacancyId")]
        [InverseProperty("ParkingReservationHistory")]
        public virtual Vacancy Vacancy { get; set; }
    }
}