// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TCC_API.Models.Entities
{
    public partial class Parking
    {
        public Parking()
        {
            ParkingOpeningHour = new HashSet<ParkingOpeningHour>();
            ParkingReservation = new HashSet<ParkingReservation>();
            ParkingReservationHistory = new HashSet<ParkingReservationHistory>();
            Vacancy = new HashSet<Vacancy>();
        }

        [Key]
        public Guid ParkingId { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Address { get; set; }
        public int Type { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Latitude { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Longitude { get; set; }
        public int LocationType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime WhenCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WhenUpdated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WhenRemoved { get; set; }
        public int SystemStatus { get; set; }

        [InverseProperty("Parking")]
        public virtual ICollection<ParkingOpeningHour> ParkingOpeningHour { get; set; }
        [InverseProperty("Parking")]
        public virtual ICollection<ParkingReservation> ParkingReservation { get; set; }
        [InverseProperty("Parking")]
        public virtual ICollection<ParkingReservationHistory> ParkingReservationHistory { get; set; }
        [InverseProperty("Parking")]
        public virtual ICollection<Vacancy> Vacancy { get; set; }
    }
}