// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TCC_API.Models.Entities
{
    [Index("ParkingId", Name = "IX_ParkingId")]
    public partial class ParkingOpeningHour : Base
    {
        public Guid ParkingId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OpeningTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ClosingTime { get; set; }
        public int Day { get; set; }

        [ForeignKey("ParkingId")]
        [InverseProperty("ParkingOpeningHour")]
        public virtual Parking Parking { get; set; }
    }
}