// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TCC_API.Models.Entities
{
    public partial class User : Base
    {
        public User()
        {
            Authentication = new HashSet<Authentication>();
        }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        public int Type { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BirthDate { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string LicenseDrive { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Authentication> Authentication { get; set; }
    }
}